srcdir = .
top_srcdir = .
top_builddir = .

AAA_SOURCES=a.cpp b.c
AAA_NAME=program_simple

PROGRAMS=AAA

MAKEFOO=$(top_srcdir)/../..

include $(MAKEFOO)/defs.mk
include $(MAKEFOO)/native.mk
include $(MAKEFOO)/main.mk

