srcdir = .
top_srcdir = .
top_builddir = .

A_SOURCES=a.cpp b.c
A_NAME=x

PROGRAMS=A

all: x

MAKEFOO=$(top_srcdir)/../../

include $(MAKEFOO)/defs.mk
include $(MAKEFOO)/native.mk
include $(MAKEFOO)/main.mk

