srcdir = .
top_srcdir = .
top_builddir = .

AAA_SOURCES=a.cpp b.c Makefile
AAA_NAME=program_simple

PROGRAMS=AAA

PRODUCT=aaa
VERSION=1.2.3-1

MAKEFOO=$(top_srcdir)/../../main.mk
MAKEFOO_USE += native
MAKEFOO_USE += src-dist
include $(MAKEFOO)

